name: pending-timeout

on: 
  workflow_call:
    inputs:
      run_id: 
        required: true
        type: number
      timeout_minutes: 
        required: true
        type: number

jobs:
  Wait-For-Timeout:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for ${{ inputs.timeout_minutes }} minutes
        run: sleep ${{inputs.timeout_minutes}}m
  Cancel-If-Still-Pending:
    runs-on: ubuntu-latest
    needs: [Wait-For-Timeout]
    steps:
      - name: Checking calling workflow state
        uses: actions/github-script@v6
        id: check-workflow-state
        with:
          result-encoding: string
          script: |
            const {status} = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{inputs.run_id}}
            })
            console.log(`Found status ${status} for run_id/attempt: ${run_id}/${attempt_number}`)

            return status
      - name: Proceed with canceling workflow due to timeout
        if: ${{steps.set-result.outputs.result == 'waiting' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{inputs.run_id}},
            });